[package]
name = "aegislib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
bincode = "1.3.3"
anyhow = "1.0.43"
sodiumoxide = "0.2.7"
signature = "1.3.1"
