[package]
name = "aegiscli"
version = "0.1.0"
edition = "2021"
description = "CLI tool for interacting with the aegisd server"

[dependencies]
aegislib = { path = "../aegislib" }
serde = { version = "1.0", features = ["derive"], default-features = false }
tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }
toml = "0.5.8"
anyhow = "1.0.43"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
clap = "3.0.0-beta.4"
directories-next = "2.0.0"
sodiumoxide = "0.2.7"
