CREATE TABLE device_cam_pics
(
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dev_id     integer REFERENCES device (id) ON DELETE CASCADE NOT NULL,
    created_at timestamp                                        NOT NULL,
    jpeg_data  bytea                                            NOT NULL
);
