CREATE TYPE event_log_level AS ENUM ('trace', 'debug', 'info', 'warn', 'error');
CREATE TABLE device_event
(
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dev_id     integer REFERENCES device (id) ON DELETE CASCADE NOT NULL,
    created_at timestamp                                        NOT NULL,
    level      event_log_level                                  NOT NULL,
    message    TEXT                                             NOT NULL,
    UNIQUE(dev_id, created_at, level, message)
);
CREATE INDEX event_dev_time_idx ON device_event (dev_id, created_at);
